# Generated by Django 2.2.2 on 2019-08-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('createdAt', models.DateField()),
                ('sourceIP', models.CharField(max_length=20)),
                ('sourcePort', models.CharField(max_length=10)),
                ('destIP', models.CharField(max_length=50)),
                ('destPort', models.IntegerField()),
                ('proto', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountryAttack',
        ),
    ]
